spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/spring_elearning?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true